/**
 * Bundled agent knowledge — generated by `npm run sync:agent-knowledge`.
 * Source of truth: Knowledge Store `wiki/agent/*.md`
 */

import { AGENT_KNOWLEDGE_DOCS, AGENT_KNOWLEDGE_ORDER } from './knowledge/generated/agent-knowledge.bundle.ts';

export function listAgentKnowledgeSlugs(): string[] {
  return [...AGENT_KNOWLEDGE_ORDER];
}

export function getAgentKnowledgeDocument(slug: string): string | undefined {
  const doc = AGENT_KNOWLEDGE_DOCS[slug];
  return doc?.trim() || undefined;
}

export function getAgentKnowledgeContext(): string {
  const slugs = listAgentKnowledgeSlugs();
  if (slugs.length === 0) {
    return '(База знаний Agent пуста. Запустите npm run sync:agent-knowledge.)';
  }

  return slugs
    .map((slug) => {
      const body = getAgentKnowledgeDocument(slug);
      if (!body) return '';
      return `## knowledge/${slug}.md\n\n${body}`;
    })
    .filter(Boolean)
    .join('\n\n---\n\n');
}

export function getAgentKnowledgeStats(): { documents: number; characters: number } {
  const slugs = listAgentKnowledgeSlugs();
  const characters = slugs.reduce((sum, slug) => sum + (getAgentKnowledgeDocument(slug)?.length ?? 0), 0);
  return { documents: slugs.length, characters };
}
